### ISSUE TITLE
Payment details broken under php 5.3

### ISSUE THREAD

**Issue by jeff1985** [paypal/rest-api-sample-app-php#15]
The readme states that this app reqires php 5.3+

However in the file /app/order/payment.php you are using the constant JSON_PRETTY_PRINT, which was defined in php 5.4 according to the docs under http://php.net/manual/de/function.json-encode.php

For me (PHP 5.3.10) using this constant causes missing output in the payment details page (no json data at all!). 

I suggest the following fix:

```php
if (defined("JSON_PRETTY_PRINT")) {
    echo $paymentDetails->toJSON(JSON_PRETTY_PRINT);
}
else {
    echo $paymentDetails->toJSON();
}
```

**Comment by jaypatel512** [comment]
You are completely right about this. I have realized this when working in REST SDK. I had to make an if-else for setting this PRETTY_PRINT. 

your code suggestion definitely makes sense. I will make the change as soon as possible, and update the sample app soon.
