### ISSUE TITLE
app/user/profile.php#L116 and L122

### ISSUE THREAD

**Issue by momikv** [paypal/rest-api-sample-app-php#17]
app/user/profile.php#L116 

incorrect - $card->getExpire_Month();
correct - $card->getExpireMonth();

app/user/profile.php#L122

incorrect - $card->getExpire_Year();
correct - $card->getExpireYear();

**Comment by jaypatel512** [comment]
Agreed. My bad on that. I will go ahead and complete that. Btw, feel free to send us a pull request, if you wish to. It is generally very easy for similar changes directly on github website.
