### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by pradeepprogramming** [paypal/rest-api-sample-app-php#21]
when i am running my application on shared hosting then it works properly but when running in vps then its is giving error that "You must run `composer install` in the sample app directory"  what should i do to resolve this problem . plz help 

thank u

**Comment by jaypatel512** [comment]
You need to run `composer install` to install all the required dependencies. This is mandatory for any composer based application. 

You can alternatively use direct download option to download entire sdk including all the dependencies.
