### ISSUE TITLE
Got Http response code 404 when accessing https://api.sandbox.paypal.com/v1/payments/payment.

### ISSUE THREAD

**Issue by muddy-28** [paypal/rest-api-sample-app-php#22]
Got Http response code 404 when accessing https://api.sandbox.paypal.com/v1/payments/payment.
<img width="1066" alt="screen shot 2016-01-29 at 9 56 29 am" src="https://cloud.githubusercontent.com/assets/7922958/12667550/cbfddfbc-c66e-11e5-9ad7-805586a87c88.png">
<img width="1434" alt="screen shot 2016-01-29 at 9 55 01 am" src="https://cloud.githubusercontent.com/assets/7922958/12667551/cc02e066-c66e-11e5-8ec3-da4de47c4c50.png">
<img width="1243" alt="screen shot 2016-01-29 at 9 54 53 am" src="https://cloud.githubusercontent.com/assets/7922958/12667552/cc09f266-c66e-11e5-9d51-58655d3b817b.png">

still getting same issue

**Comment by jaypatel512** [comment]
Can you please update the clientID and secret of your account to get proper credentials. Can you please add logs if this issue is still not resolved. 

Closing this issue for now based on the inactivity.

**Comment by ArunPadmanabhan** [comment]
Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment.
